
string1 = openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt \
    | openssl rsa -pubin -outform der 2>/dev/null \
    | openssl dgst -sha256 -hex \
    | sed 's/^.* //'

kubeadm token list

string2 = sed -n '/^The default bootstrap token generated by kubeadm init*,$ p';

string3 = sudo kubeadm join
    --token= string2
    --discovery-token-ca-cert-hash sh2256:string1

    echo string3 >> file.txt

git clone https://github.com/ShadownightLP/Kubernetes
git add file.txt

read -p 'Message to commit : ' uservar
git commit -m uservar
git commit -a
#kubeadm token create --print-join-command
#string3= initscript.sh | sed -n '/^kubeadm join*,$ p';
