apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: echo-ingress
    annotations:
        haproxy.org/path-rewrite: "/"
spec:
    rules:
    - http:
        paths:
        - path: /echo
          backend:
            serviceName: web-ingress
            servicePort: 80